apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - default_sa.yaml
  - vault.yaml
  - talos.yaml
  - etcdsnapshot.yaml
  - psql-hass.yaml
  - psql-paperless.yaml
