apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goldilocks

resources:
  - namespace.yaml
  - tailscale.yaml

helmCharts:
- name: goldilocks
  includeCRDs: true
  namespace: goldilocks
  releaseName: goldilocks
  version: 10.2.0
  repo: https://charts.fairwinds.com/stable
  valuesInline:
    dashboard:
      replicaCount: 1
    controller:
      enabled: true
    vpa:
      enabled: true
